### PR TITLE
feature / enroll events

### PR DESCRIPTION
**Pull request by jbpextra**
Implemented

- enroll to an event

- unenroll from an event

- retrieve all users enrolled in an event

- retrieve all events a user has unrolled

All tests pass on local.

### CODE REVIEW

**Comment by jbpextra** [comment]
Test coverage is now 100%

**Review by sergiowalls — CHANGES_REQUESTED** [review]
el post de un enrollment deberia ser sobre la uri /enrollments
si el evento no tiene fecha al guardar el enrollment no petará por null pointer? EnrollmentService linea 27
si no hay content no pasarselo: test linea 58
doPrint y return fuera: test linea 103 y 124
nombres de las funciones de los tests empiezan en minuscula

**Comment by jbpextra** [comment]
Done @sergiowalls

**Comment by sergiowalls** [comment]
He fet checkout d'aquesta branca i em peten la majoria de tests afegits i alguns ja existents

image

**Comment by jbpextra** [comment]
fixed

**Pull request merged**
